server.port=9102
spring.application.name=eureka-server

# Mode standalone (pas de cluster)
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
spring.cloud.config.import-check.enabled=false

# Pour éviter les timeouts en local
eureka.server.maxThreadsForPeerReplication=0
