# H2 & JPA (coté MS Produits)
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.sql-script-encoding=UTF-8

# Config métier externalisée
mes-configs.limitDeProduits=4

#Eureka :indique l'URL d'Eureka à laquelle il faut s'enregistrer 
eureka.client.service-url.defaultZone=http://localhost:9102/eureka/
 
#Actuator : management.endpoints.web.exposure.include=* 
management.endpoints.web.expose=info, health, refresh 
